services:
  db:
    image: postgres
    init: true
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_DB_FILE: /run/secrets/postgres_db
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
  web:
    build:
      secrets:
        - debug
        - secret_key
        - allowed_hosts
        - internal_ips
        - postgres_db
        - postgres_password
        - postgres_user
        - postgres_port
      args:
        DEBUG: /run/secrets/DEBUG
        POSTGRES_HOST: db
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db

secrets:
  debug:
    file: /opt/secrets/aba/DEBUG
  secret_key:
    file: /opt/secrets/aba/SECRET_KEY
  allowed_hosts:
    file: /opt/secrets/aba/ALLOWED_HOSTS
  internal_ips:
    file: /opt/secrets/aba/INTERNAL_IPS
  postgres_db:
    file: /opt/secrets/aba/POSTGRES_DB
  postgres_password:
    file: /opt/secrets/aba/POSTGRES_PASSWORD
  postgres_user:
    file: /opt/secrets/aba/POSTGRES_USER
  postgres_port:
    file: /opt/secrets/aba/POSTGRES_PORT

volumes:
  postgres_data:
