[tool.poetry]
name = "abarocks"
version = "2.0.0"
description = "ABA Rocks is an open-source web app for aspiring behavior analysts!"
authors = [
    "Alex Raymond <harblz@gmail.com>",
    "Kyle Jensen <kyle@nullandvoid.digital>"
]
license = "n"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0"
django-bootstrap5 = "^24.2"
whitenoise = "^6.7"
django-htmx = "^1.19"
stripe = "^10.11"
django-taggit = "^6.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
django-debug-toolbar = "^5.0"
django-extensions = "^3.2"
black = "^24.8"
ipython = "^8.27"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
