# Generated by Django 5.1.3 on 2024-12-15 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_profile_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="session",
        ),
    ]
