# Generated by Django 5.2rc1 on 2025-03-29 16:36

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_profile_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="PageContent",
            fields=[
                (
                    "view",
                    models.SlugField(
                        db_comment="The view that corresponds to the specified path in the request object",
                        max_length=200,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("heading", models.CharField(blank=True, max_length=255, null=True)),
                ("subheading", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "body",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Page Body"
                    ),
                ),
            ],
        ),
    ]
