# Generated by Django 5.2rc1 on 2025-04-12 21:34

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_navlink_pagecontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "slug",
                    models.SlugField(
                        db_comment="The view that corresponds to the specified path in the request object",
                        max_length=200,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("app", models.CharField(max_length=25)),
                ("view", models.CharField(max_length=100)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("subtitle", models.CharField(blank=True, max_length=255, null=True)),
                ("blurb", models.TextField(blank=True, null=True)),
                (
                    "body",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Page Body"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="NavLink",
        ),
        migrations.DeleteModel(
            name="PageContent",
        ),
    ]
