# Generated by Django 5.2rc1 on 2025-04-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_page_delete_navlink_delete_pagecontent"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="page",
            table_comment="Stores data for Page content and Navbar Links",
        ),
        migrations.AlterField(
            model_name="page",
            name="app",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="view",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
