# Generated by Django 5.2rc1 on 2025-04-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_page_table_comment_alter_page_app_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(
                blank=True,
                db_comment="The view that corresponds to the specified path in the request object",
                max_length=200,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
