# Generated by Django 5.2rc1 on 2025-04-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_page_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(
                db_comment="The view that corresponds to the specified path in the request object",
                max_length=200,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="view",
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
    ]
