# Generated by Django 5.2rc1 on 2025-04-12 22:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_page_slug_alter_page_view"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="slug",
        ),
        migrations.AddField(
            model_name="page",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="nav",
            field=models.BooleanField(
                default=False, verbose_name="Include in Navigation?"
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="params",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True, max_length=25, null=True, verbose_name="Path Parameters"
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="app",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="App Namespace"
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="view",
            field=models.CharField(max_length=100, verbose_name="URL Name"),
        ),
    ]
