# Generated by Django 5.2rc1 on 2025-04-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_page_slug_page_id_page_nav_page_params_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="root",
            field=models.BooleanField(
                default=False, verbose_name="Is Navigation Root?"
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="nav",
            field=models.BooleanField(
                default=False,
                verbose_name="Include in Navigation?",
            ),
        ),
    ]
