# Generated by Django 5.2 on 2025-04-14 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_page_root_alter_page_nav"),
    ]

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app", models.CharField(max_length=25, verbose_name="App Namespace")),
                ("nav_position", models.IntegerField(verbose_name="Nav Position")),
            ],
        ),
        migrations.AlterField(
            model_name="page",
            name="app",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="app_two",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.app",
            ),
        ),
    ]
