# Generated by Django 5.2 on 2025-04-14 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_app_alter_page_app_page_app_two"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="app_two",
        ),
        migrations.CreateModel(
            name="NavLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nav",
                    models.BooleanField(
                        default=False, verbose_name="Include in Navigation?"
                    ),
                ),
                (
                    "root",
                    models.BooleanField(
                        default=False, verbose_name="Is Navigation Root?"
                    ),
                ),
                ("root_pos", models.IntegerField(blank=True, null=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.page"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="App",
        ),
    ]
