# Generated by Django 5.2 on 2025-04-14 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_page_app_two_navlinks_delete_app"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="navlinks",
            name="nav",
        ),
        migrations.RemoveField(
            model_name="page",
            name="root",
        ),
    ]
