# Generated by Django 5.2 on 2025-04-14 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_remove_navlinks_nav_remove_page_root"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navlinks",
            name="page",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="core.page"
            ),
        ),
    ]
