# Generated by Django 5.2 on 2025-04-14 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_navlinks_page"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NavLinks",
            new_name="NavLink",
        ),
    ]
