# Generated by Django 5.2 on 2025-04-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_rename_navlinks_navlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="navlink",
            name="has_children",
            field=models.BooleanField(default=False, verbose_name="Has child pages?"),
        ),
    ]
