# Generated by Django 5.2 on 2025-04-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_navlink_has_children"),
    ]

    operations = [
        migrations.AddField(
            model_name="navlink",
            name="label",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
