# Generated by Django 5.1.3 on 2024-11-29 19:35

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("learn", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultipleChoiceAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Answer Text")),
            ],
            options={
                "db_table_comment": "Table of multiple choice answers",
                "default_related_name": "answers",
            },
        ),
        migrations.CreateModel(
            name="MultipleChoiceQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="Question Text"
                    ),
                ),
                (
                    "hint",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Question Hint"
                    ),
                ),
                (
                    "answer",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="quiz.multiplechoiceanswer",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learn.contentarea",
                    ),
                ),
            ],
            options={
                "verbose_name": "Multiple Choice Question",
                "db_table_comment": "All multiple choice questions",
                "default_related_name": "multiple_choice_questions",
            },
        ),
        migrations.AddField(
            model_name="multiplechoiceanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.multiplechoicequestion",
            ),
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "slug",
                    models.SlugField(primary_key=True, serialize=False, unique=True),
                ),
                ("number", models.IntegerField(default=1)),
                ("desc", models.CharField(max_length=100, verbose_name="Description")),
                (
                    "timed",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="Timed?"
                    ),
                ),
                (
                    "time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Time in minutes"
                    ),
                ),
                ("areas", models.ManyToManyField(blank=True, to="learn.contentarea")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="learn.course"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Quizzes",
                "db_table_comment": "Table of available quizzes",
                "default_related_name": "quizzes",
            },
        ),
        migrations.CreateModel(
            name="TrueFalseQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="Question Text"
                    ),
                ),
                (
                    "hint",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Question Hint"
                    ),
                ),
                ("answer", models.BooleanField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learn.contentarea",
                    ),
                ),
            ],
            options={
                "verbose_name": "True/False Question",
                "db_table_comment": "All True/False Questions",
                "default_related_name": "true_false_questions",
            },
        ),
    ]
