# Generated by Django 5.1.2 on 2024-11-03 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("learn", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(unique=True, verbose_name="Question Text")),
                ("one", models.TextField(verbose_name="Question One")),
                ("two", models.TextField(verbose_name="Question Two")),
                (
                    "three",
                    models.TextField(
                        blank=True, null=True, verbose_name="Question Three"
                    ),
                ),
                (
                    "four",
                    models.TextField(
                        blank=True, null=True, verbose_name="Question Four"
                    ),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="quiz.question",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learn.contentarea",
                    ),
                ),
            ],
            options={
                "db_table_comment": "Table of all questions from any quiz",
                "default_related_name": "questions",
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "slug",
                    models.SlugField(primary_key=True, serialize=False, unique=True),
                ),
                ("number", models.IntegerField(default=1)),
                ("desc", models.CharField(max_length=100, verbose_name="Description")),
                ("timed", models.BooleanField(default=False, verbose_name="Timed?")),
                (
                    "time",
                    models.DurationField(
                        blank=True, default=0, null=True, verbose_name="Time in minutes"
                    ),
                ),
                ("areas", models.ManyToManyField(blank=True, to="learn.contentarea")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="learn.course"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Quizzes",
                "db_table_comment": "Table of available quizzes",
                "default_related_name": "quizzes",
            },
        ),
    ]
