# Generated by Django 6.0.3 on 2026-04-12 21:34

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("learn", "0005_remove_course_course_data_remove_course_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="Question Text"
                    ),
                ),
                (
                    "hint",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Question Hint"
                    ),
                ),
                ("disabled", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learn.contentarea",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MultipleChoiceQuestion",
            fields=[
                (
                    "basequestion_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="quiz.basequestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Multiple Choice Question",
                "db_table_comment": "All multiple choice questions",
            },
            bases=("quiz.basequestion",),
        ),
        migrations.CreateModel(
            name="TrueFalseQuestion",
            fields=[
                (
                    "basequestion_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="quiz.basequestion",
                    ),
                ),
                ("answer", models.BooleanField()),
            ],
            options={
                "verbose_name": "True/False Question",
                "db_table_comment": "All True/False Questions",
            },
            bases=("quiz.basequestion",),
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "slug",
                    models.SlugField(primary_key=True, serialize=False, unique=True),
                ),
                ("number", models.IntegerField(default=1)),
                ("desc", models.CharField(max_length=100, verbose_name="Description")),
                (
                    "timed",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="Timed?"
                    ),
                ),
                (
                    "time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Time in minutes"
                    ),
                ),
                ("areas", models.ManyToManyField(blank=True, to="learn.contentarea")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="learn.course"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Quizzes",
                "db_table_comment": "Table of available quizzes",
                "default_related_name": "quizzes",
            },
        ),
        migrations.CreateModel(
            name="QuizProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session", models.CharField(max_length=150)),
                ("quiz", models.SlugField()),
                ("index", models.IntegerField(default=0)),
                (
                    "timed",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="Timed?"
                    ),
                ),
                (
                    "time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Time in minutes"
                    ),
                ),
                ("key", models.JSONField(default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table_comment": "Quiz progress data",
            },
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quiz", models.SlugField()),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("elapsed", models.DurationField(blank=True, null=True)),
                ("total", models.IntegerField()),
                ("correct", models.IntegerField()),
                ("score", models.IntegerField(default=0)),
                ("key", models.JSONField(default=dict)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "default_related_name": "quiz_results",
            },
        ),
        migrations.CreateModel(
            name="MultipleChoiceAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Answer Text"),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Is Correct?"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.multiplechoicequestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Multiple Choice Answer",
                "db_table_comment": "Table of multiple choice answers",
                "default_related_name": "answers",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_correct", True)),
                        fields=("question",),
                        name="unique_correct",
                    )
                ],
            },
        ),
    ]
