# Generated by Django 5.1.1 on 2024-11-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=models.CharField(
                blank=True,
                choices=[("A", "one"), ("B", "two"), ("C", "three"), ("D", "four")],
                max_length=4,
                null=True,
            ),
        ),
    ]
