# Generated by Django 5.1.3 on 2024-12-15 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="multiplechoicequestion",
            name="disabled",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="truefalsequestion",
            name="disabled",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name="QuizProgress",
            fields=[
                (
                    "quiz",
                    models.SlugField(primary_key=True, serialize=False, unique=True),
                ),
                ("index", models.IntegerField(default=0)),
                (
                    "timed",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="Timed?"
                    ),
                ),
                (
                    "time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Time in minutes"
                    ),
                ),
                ("key", models.JSONField(default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table_comment": "Quiz progress data",
            },
        ),
    ]
