# Generated by Django 5.1.2 on 2024-11-06 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0001_initial"),
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultipleChoiceAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(unique=True, verbose_name="Answer Text")),
            ],
            options={
                "db_table_comment": "Table of multiple choice answers",
                "default_related_name": "answers",
            },
        ),
        migrations.AlterField(
            model_name="quiz",
            name="time",
            field=models.DurationField(
                blank=True, null=True, verbose_name="Time in minutes"
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="timed",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Timed?"
            ),
        ),
        migrations.CreateModel(
            name="MultipleChoiceQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(unique=True, verbose_name="Question Text")),
                (
                    "answer",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="quiz.multiplechoiceanswer",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learn.contentarea",
                    ),
                ),
            ],
            options={
                "verbose_name": "Multiple Choice Question",
                "db_table_comment": "All multiple choice questions",
                "default_related_name": "multiple_choice_questions",
            },
        ),
        migrations.AddField(
            model_name="multiplechoiceanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.multiplechoicequestion",
            ),
        ),
        migrations.CreateModel(
            name="TrueFalseQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(unique=True, verbose_name="Question Text")),
                ("answer", models.BooleanField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learn.contentarea",
                    ),
                ),
            ],
            options={
                "verbose_name": "True/False Question",
                "db_table_comment": "All True/False Questionse",
                "default_related_name": "true_false_questions",
            },
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
