# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='unit_name',
            field=models.CharField(default='RBT', max_length=200),
            preserve_default=False,
        ),
    ]
