# Generated by Django 5.1.2 on 2024-11-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_multiplechoiceanswer_alter_quiz_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="multiplechoicequestion",
            name="hint",
            field=models.TextField(blank=True, null=True, verbose_name="Question Hint"),
        ),
        migrations.AddField(
            model_name="truefalsequestion",
            name="hint",
            field=models.TextField(blank=True, null=True, verbose_name="Question Hint"),
        ),
    ]
