# Generated by Django 5.1.3 on 2024-12-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_quizprogress_session_alter_quizprogress_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizprogress",
            name="quiz",
            field=models.SlugField(),
        ),
        migrations.AddField(
            model_name="quizprogress",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
