# Generated by Django 5.1.2 on 2024-11-11 20:35

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_multiplechoicequestion_hint_truefalsequestion_hint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multiplechoicequestion",
            name="hint",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Question Hint"
            ),
        ),
        migrations.AlterField(
            model_name="multiplechoicequestion",
            name="text",
            field=django_ckeditor_5.fields.CKEditor5Field(
                unique=True, verbose_name="Question Text"
            ),
        ),
        migrations.AlterField(
            model_name="truefalsequestion",
            name="hint",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Question Hint"
            ),
        ),
        migrations.AlterField(
            model_name="truefalsequestion",
            name="text",
            field=django_ckeditor_5.fields.CKEditor5Field(
                unique=True, verbose_name="Question Text"
            ),
        ),
    ]
