# Generated by Django 5.1.4 on 2025-01-10 16:51

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0004_alter_course_description_alter_course_subtitle"),
        ("quiz", "0004_quizprogress_id_alter_quizprogress_quiz"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="multiplechoicequestion",
            name="category",
        ),
        migrations.RemoveField(
            model_name="multiplechoicequestion",
            name="disabled",
        ),
        migrations.RemoveField(
            model_name="multiplechoicequestion",
            name="hint",
        ),
        migrations.RemoveField(
            model_name="multiplechoicequestion",
            name="id",
        ),
        migrations.RemoveField(
            model_name="multiplechoicequestion",
            name="text",
        ),
        migrations.RemoveField(
            model_name="truefalsequestion",
            name="category",
        ),
        migrations.RemoveField(
            model_name="truefalsequestion",
            name="disabled",
        ),
        migrations.RemoveField(
            model_name="truefalsequestion",
            name="hint",
        ),
        migrations.RemoveField(
            model_name="truefalsequestion",
            name="id",
        ),
        migrations.RemoveField(
            model_name="truefalsequestion",
            name="text",
        ),
        migrations.CreateModel(
            name="BaseQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="Question Text"
                    ),
                ),
                (
                    "hint",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Question Hint"
                    ),
                ),
                ("disabled", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learn.contentarea",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="multiplechoicequestion",
            name="basequestion_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="quiz.basequestion",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="truefalsequestion",
            name="basequestion_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="quiz.basequestion",
            ),
            preserve_default=False,
        ),
    ]
