# Generated by Django 5.1.2 on 2024-11-12 21:56

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_alter_multiplechoicequestion_hint_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multiplechoicequestion",
            name="text",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Question Text"),
        ),
        migrations.AlterField(
            model_name="truefalsequestion",
            name="text",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Question Text"),
        ),
    ]
