# Generated by Django 5.1.4 on 2025-01-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0005_remove_multiplechoicequestion_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="multiplechoiceanswer",
            options={
                "default_related_name": "answers",
                "verbose_name": "Multiple Choice Answer",
            },
        ),
        migrations.AlterModelOptions(
            name="multiplechoicequestion",
            options={"verbose_name": "Multiple Choice Question"},
        ),
        migrations.AlterModelOptions(
            name="truefalsequestion",
            options={"verbose_name": "True/False Question"},
        ),
        migrations.AddField(
            model_name="basequestion",
            name="type",
            field=models.CharField(max_length=50, verbose_name="Question Type"),
            preserve_default=False,
        ),
    ]
