# Generated by Django 5.1.2 on 2024-11-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0005_alter_multiplechoicequestion_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multiplechoiceanswer",
            name="text",
            field=models.TextField(verbose_name="Answer Text"),
        ),
    ]
