# Generated by Django 5.1.4 on 2025-01-13 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("quiz", "0006_alter_multiplechoiceanswer_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basequestion",
            name="type",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
