# Generated by Django 5.1.6 on 2025-03-17 00:20

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0007_alter_basequestion_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multiplechoiceanswer",
            name="text",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Answer Text"),
        ),
    ]
