# Generated by Django 2.0.4 on 2018-04-11 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_question_unit_name'),
        ('quiz', '0005_auto_20180405_1916'),
    ]

    operations = [
    ]
