# Generated by Django 2.0.4 on 2018-05-09 02:40

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0008_merge_20180411_1902"),
    ]

    operations = [
        migrations.CreateModel(
            name="Difficulty",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("difficulty_name", models.CharField(max_length=25)),
                ("difficulty_description", ckeditor.fields.CKEditor5Field()),
            ],
        ),
        migrations.AlterField(
            model_name="unit",
            name="unit_description",
            field=ckeditor.fields.CKEditor5Field(),
        ),
        migrations.AddField(
            model_name="question",
            name="difficulty",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.Difficulty",
            ),
            preserve_default=False,
        ),
    ]
