# Generated by Django 5.2 on 2025-06-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0009_alter_quizprogress_quiz_alter_quizprogress_session_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizprogress",
            name="quiz",
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name="quizprogress",
            name="session",
            field=models.CharField(max_length=150),
        ),
    ]
