# Generated by Django 2.0.4 on 2018-06-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20180514_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_target',
            field=models.CharField(default='RBT', max_length=50),
        ),
    ]
