# Generated by Django 5.2 on 2025-07-01 02:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0011_alter_quizresults_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="QuizResults",
            new_name="QuizResult",
        ),
        migrations.AlterModelOptions(
            name="quizresult",
            options={"default_related_name": "quiz_results"},
        ),
    ]
