# Generated by Django 6.0 on 2025-12-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0014_result_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="multiplechoiceanswer",
            name="is_correct",
            field=models.BooleanField(default=False, verbose_name="Is Correct?"),
        ),
    ]
