# Generated by Django 2.0.4 on 2018-07-27 00:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_auto_20180715_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='form_description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
