# Generated by Django 6.0 on 2025-12-21 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0015_multiplechoiceanswer_is_correct"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="multiplechoicequestion",
            name="answer",
        ),
    ]
