# Generated by Django 2.0.4 on 2018-08-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_form_form_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='form_short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
