# Generated by Django 6.0 on 2025-12-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0017_remove_multiplechoicequestion_answer"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="multiplechoiceanswer",
            constraint=models.UniqueConstraint(
                fields=("question", "is_correct"), name="unique_correct"
            ),
        ),
    ]
