# Generated by Django 2.0.8 on 2018-11-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_form_form_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='form_name',
            field=models.CharField(default='A', max_length=75),
        ),
        migrations.AlterField(
            model_name='form',
            name='form_short_name',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
