# Generated by Django 6.0.2 on 2026-03-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0018_multiplechoiceanswer_unique_correct"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                # If a previous attempt created the index but not the constraint,
                # adding the constraint will fail with "relation already exists".
                'ALTER TABLE "quiz_multiplechoiceanswer" DROP CONSTRAINT IF EXISTS "unique_correct";',
                'DROP INDEX IF EXISTS "unique_correct";',
            ],
            reverse_sql=[
                # Best-effort rollback: remove the constraint/index if present.
                'ALTER TABLE "quiz_multiplechoiceanswer" DROP CONSTRAINT IF EXISTS "unique_correct";',
                'DROP INDEX IF EXISTS "unique_correct";',
            ],
        ),
        migrations.AddConstraint(
            model_name="multiplechoiceanswer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_correct", True)),
                fields=("question",),
                name="unique_correct",
            ),
        ),
    ]
