# Generated by Django 2.1.3 on 2019-01-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_auto_20181106_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='error_reports',
            field=models.IntegerField(default=0),
        ),
    ]
