# Generated by Django 2.1.3 on 2019-04-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_quiz_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_scores',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
