# Generated by Django 2.1.3 on 2019-04-27 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_quiz_scores_score'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiz_Scores',
            new_name='QuizScore',
        ),
    ]
