# Generated by Django 2.1.3 on 2019-04-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_auto_20190427_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizscore',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
    ]
