# Generated by Django 2.1.3 on 2019-04-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_auto_20190427_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizscore',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
