# Generated by Django 2.1.8 on 2019-04-28 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_auto_20190427_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizScoreSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Quiz Score Summary',
                'verbose_name_plural': 'Quiz Scores Summary',
                'proxy': True,
                'indexes': [],
            },
            bases=('quiz.quizscore',),
        ),
    ]
