# Generated by Django 2.0 on 2018-06-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pages',
            options={'verbose_name_plural': 'Site Pages'},
        ),
        migrations.AddField(
            model_name='pages',
            name='slug',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
