# Generated by Django 2.0 on 2018-06-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20180621_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
