# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 19:54
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="text",
            field=ckeditor.fields.CKEditor5Field(),
        ),
    ]
