# Generated by Django 5.1.1 on 2024-11-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="subtitle",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
