# Generated by Django 5.2 on 2025-05-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_subtitle"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="text",
            new_name="body",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="page_views",
            new_name="likes",
        ),
        migrations.RemoveField(
            model_name="category",
            name="category_description",
        ),
        migrations.RemoveField(
            model_name="category",
            name="category_name",
        ),
        migrations.RemoveField(
            model_name="post",
            name="is_pinned",
        ),
        migrations.RemoveField(
            model_name="post",
            name="meta",
        ),
        migrations.RemoveField(
            model_name="post",
            name="pic",
        ),
        migrations.RemoveField(
            model_name="post",
            name="snippet_size",
        ),
        migrations.RemoveField(
            model_name="post",
            name="status",
        ),
        migrations.AddField(
            model_name="category",
            name="category",
            field=models.CharField(default="Default Category", max_length=50),
        ),
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AddField(
            model_name="post",
            name="draft",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="pinned",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="published",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="views",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
