# Generated by Django 2.0.4 on 2018-06-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='page_views',
            field=models.IntegerField(default=0),
        ),
    ]
