# Generated by Django 2.0 on 2018-06-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_page_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet_size',
            field=models.IntegerField(default=150),
        ),
    ]
