# Generated by Django 2.0 on 2018-06-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_snippet_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='qq', max_length=200),
            preserve_default=False,
        ),
    ]
