# Generated by Django 2.0.4 on 2018-06-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180622_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_pinned',
            field=models.NullBooleanField(help_text='qq'),
        ),
    ]
