# Generated by Django 2.0.4 on 2018-06-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_is_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_pinned',
            field=models.NullBooleanField(default=False, help_text='qq'),
        ),
    ]
