# Generated by Django 2.0.4 on 2018-06-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180628_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_pinned',
            field=models.NullBooleanField(default='False', help_text="Pinning a blog post makes it stick to the 'pinned items' bar on the front page of the site. Try not to pin too many posts because it'll look crazy"),
        ),
        migrations.AlterField(
            model_name='post',
            name='snippet_size',
            field=models.IntegerField(default=150, help_text="The snippet_size determines how much of a text to 'preview' before the post shows the 'read more' button"),
        ),
    ]
