# Generated by Django 2.0.4 on 2018-06-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180629_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_pinned',
            field=models.NullBooleanField(default=False, help_text="Pinning a blog post makes it stick to the 'pinned items' bar on the front page of the site. Try not to pin too many posts because it'll look crazy"),
        ),
    ]
