# Generated by Django 2.0.4 on 2018-07-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20180629_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pic',
            field=models.CharField(help_text="This is the 'splash' picture that will be shown to the user as a header for each post", max_length=200, null=True),
        ),
    ]
