# Generated by Django 2.0.4 on 2018-07-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
