# Generated by Django 2.0.4 on 2018-07-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.CharField(help_text="This is the 'splash' picture that will be shown to the user as a header for each post. You can leave it blank.", max_length=200, null=True),
        ),
    ]
