# Generated by Django 2.0.4 on 2018-08-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20180729_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.CharField(blank=True, help_text="This is the 'splash' picture that will be shown to the user as a header for each post. You can leave it blank.", max_length=200, null=True),
        ),
    ]
