# Generated by Django 2.0.8 on 2018-11-07 08:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='Default Category', max_length=75)),
                ('category_description', ckeditor.fields.RichTextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
