# Generated by Django 2.0.8 on 2019-01-01 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20181115_1908'),
        ('blog', '0023_auto_20181227_2255'),
    ]

    operations = [
    ]
