# Generated by Django 2.0.8 on 2019-03-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_merge_20190101_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.CharField(blank=True, help_text="This is the 'splash' picture that will be shown to the user as a header for each post. You can leave it blank. FOR POSTS SERVED UP ON THE SITE, THEY SHOULD START WITH /static/img/", max_length=200, null=True),
        ),
    ]
