# Generated by Django 5.1.1 on 2024-09-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20190313_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_pinned',
            field=models.BooleanField(blank=True, help_text="Pinning a blog post makes it stick to the 'pinned items' bar on the front page of the site. Try not to pin too many posts because it'll look crazy", null=True),
        ),
    ]
