# Generated by Django 5.1.1 on 2024-09-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0026_alter_post_is_pinned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
