# Generated by Django 2.1.3 on 2018-12-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluency', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='Flashcard_hint',
            new_name='flashcard_hint',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='flashcard_choices',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='certification',
            field=models.CharField(default='BCBA', max_length=25),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_target',
            field=models.CharField(default='BCBA', max_length=50),
        ),
    ]
