# Generated by Django 2.1.3 on 2019-01-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluency', '0003_auto_20181227_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='deck_name',
            field=models.CharField(default='1', max_length=75),
        ),
        migrations.AlterField(
            model_name='task',
            name='certification',
            field=models.CharField(default='RBT', max_length=25),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_version',
            field=models.CharField(default='2019', max_length=50),
        ),
    ]
