# Generated by Django 2.1.3 on 2019-01-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluency', '0004_auto_20190101_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='error_reports',
            field=models.IntegerField(default=0),
        ),
    ]
