# Generated by Django 2.1.3 on 2019-04-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluency', '0007_fluency_timed_scores_fluency_untimed_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluency_timed_scores',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='fluency_untimed_scores',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='fluency_timed_scores',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fluency_untimed_scores',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
