# Generated by Django 2.1.3 on 2019-04-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluency', '0008_auto_20190427_0958'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fluency_Timed_Scores',
            new_name='FluencyTimedScores',
        ),
        migrations.RenameModel(
            old_name='Fluency_Untimed_Scores',
            new_name='FluencyUntimedScores',
        ),
    ]
