# Generated by Django 2.1.3 on 2019-04-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluency', '0010_auto_20190427_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluencytimedscore',
            name='time_elapsed',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
    ]
