# Generated by Django 2.1.8 on 2019-04-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluency', '0012_auto_20190427_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluencytimedscore',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
