# Generated by Django 2.1.8 on 2019-05-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluency', '0013_auto_20190427_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='task_list_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='task_list_text',
            field=models.CharField(default=None, max_length=10000, null=True),
        ),
    ]
