# Generated by Django 2.1.8 on 2019-05-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluency', '0014_auto_20190505_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='task_list_name',
            new_name='task_list_data',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='task_list_text',
        ),
    ]
