# Generated by Django 2.1.8 on 2019-05-14 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluency', '0015_auto_20190505_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluencyTimedScoreSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Fluency Timed Score Summary',
                'verbose_name_plural': 'Fluency Timed Scores Summary',
                'proxy': True,
                'indexes': [],
            },
            bases=('fluency.fluencytimedscore',),
        ),
        migrations.CreateModel(
            name='FluencyUntimedScoreSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Fluency Untimed Score Summary',
                'verbose_name_plural': 'Fluency Untimed Scores Summary',
                'proxy': True,
                'indexes': [],
            },
            bases=('fluency.fluencyuntimedscore',),
        ),
    ]
