# Generated by Django 6.0.3 on 2026-04-12 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("learn", "0005_remove_course_course_data_remove_course_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("back", models.CharField(max_length=50)),
                ("front", models.CharField(max_length=100)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("back", "front"), name="unique_cards"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Deck",
            fields=[
                (
                    "slug",
                    models.SlugField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "cards",
                    models.ManyToManyField(related_name="decks", to="safmeds.card"),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="learn.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("correct", models.IntegerField(default=0)),
                ("incorrect", models.IntegerField(default=0)),
                ("score", models.IntegerField(default=0)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="safmeds.deck"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "default_related_name": "safmeds_results",
            },
        ),
    ]
