# Generated by Django 5.1.6 on 2025-03-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("safmeds", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deck",
            name="id",
        ),
        migrations.AlterField(
            model_name="deck",
            name="slug",
            field=models.SlugField(primary_key=True, serialize=False, unique=True),
        ),
    ]
