# Generated by Django 5.1.6 on 2025-03-22 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0004_alter_course_description_alter_course_subtitle"),
        ("safmeds", "0002_remove_deck_id_alter_deck_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="learn.course",
            ),
            preserve_default=False,
        ),
    ]
