# Generated by Django 5.2rc1 on 2025-03-30 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("safmeds", "0003_deck_subject"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deck",
            old_name="deck",
            new_name="cards",
        ),
    ]
