# Generated by Django 5.2rc1 on 2025-03-30 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("safmeds", "0004_rename_deck_deck_cards"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deck",
            name="cards",
        ),
    ]
