# Generated by Django 5.2rc1 on 2025-03-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("safmeds", "0005_remove_deck_cards"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="cards",
            field=models.ManyToManyField(related_name="decks", to="safmeds.card"),
        ),
    ]
