events {
  worker_connections 1024; # increase if you have lots of clients
  accept_mutex off; # set to 'on' if nginx worker_processes > 1
  # 'use epoll;' to enable for Linux 2.6+
  # 'use kqueue;' to enable for FreeBSD, OSX
}

http {
    upstream abarocks.nullandvoid.digital {
        server 172.195.156.219:8000 fail_timeout=0;
    }
    include mime.types;
    default_type  application/octet-stream;
    server {
        # if no Host match, close the connection to prevent host spoofing
        listen 80 default_server;
        return 444;
    }
    server {
        listen 80 deferred;
        keepalive_timeout 5;
        server_name abarocks.nullandvoid.digital;

        location /static/ {
            alias /var/www/html/static/;
        }

        location / {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $http_host;
            proxy_redirect off;
            proxy_pass https://web:8000;
        }
    }
}