# Generated by Django 2.1.8 on 2019-05-05 12:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_description', ckeditor.fields.RichTextField()),
                ('course_target', models.CharField(default='RBT', max_length=50)),
            ],
        ),
    ]
