# Generated by Django 5.1.2 on 2024-11-03 04:13

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=10, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image", models.CharField(max_length=250, null=True)),
                ("description", models.TextField(null=True)),
                ("course_data", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table_comment": "The competency, license, or topic of interest",
            },
        ),
        migrations.CreateModel(
            name="ContentArea",
            fields=[
                (
                    "slug",
                    models.SlugField(primary_key=True, serialize=False, unique=True),
                ),
                ("letter", models.CharField(max_length=1)),
                ("section", models.IntegerField(blank=True, null=True)),
                ("area", models.CharField(max_length=50)),
                ("weight", models.IntegerField()),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_areas",
                        to="learn.course",
                    ),
                ),
            ],
            options={
                "db_table_comment": "The content areas for each Course",
                "default_related_name": "content_areas",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page", models.IntegerField()),
                ("title", models.CharField(max_length=100)),
                ("content", django_ckeditor_5.fields.CKEditor5Field()),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learn.contentarea",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="learn.course"
                    ),
                ),
            ],
            options={
                "db_table_comment": "Lesson pages for each course",
                "default_related_name": "lessons",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "slug",
                    models.SlugField(primary_key=True, serialize=False, unique=True),
                ),
                ("task", models.IntegerField()),
                ("task_desc", models.TextField()),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learn.contentarea",
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="learn.course"
                    ),
                ),
            ],
            options={
                "db_table_comment": "Tasks for RBT, BCaBA, and BCBA according to the BACB",
                "default_related_name": "tasks",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("license", "area", "task"), name="unique_tasks"
                    )
                ],
            },
        ),
    ]
