# Generated by Django 5.1.1 on 2024-12-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="subtitle",
            field=models.TextField(null=True),
        ),
    ]
