# Generated by Django 5.1.1 on 2024-10-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
