# Generated by Django 5.1.3 on 2024-12-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0002_course_subtitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="course",
            name="subtitle",
            field=models.CharField(null=True),
        ),
    ]
