# Generated by Django 5.1.1 on 2024-10-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0002_alter_course_course_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_desc",
            field=models.TextField(),
        ),
    ]
