# Generated by Django 5.1.3 on 2024-12-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0003_alter_course_image_alter_course_subtitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="subtitle",
            field=models.CharField(blank=True, null=True),
        ),
    ]
