# Generated by Django 2.1.8 on 2019-06-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20190630_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
