# Generated by Django 5.2rc1 on 2025-04-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0004_alter_course_description_alter_course_subtitle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="course_data",
        ),
        migrations.RemoveField(
            model_name="course",
            name="image",
        ),
    ]
