# Generated by Django 5.1.1 on 2024-10-06 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0005_remove_course_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="weights",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="learn.contentarea",
            ),
        ),
    ]
