# Generated by Django 5.1.1 on 2024-10-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0007_remove_course_weights"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
