# Generated by Django 2.1.8 on 2019-07-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_lessonpage_lesson_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonpage',
            name='slug',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
