# Generated by Django 5.1.1 on 2024-10-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0008_course_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
