# Generated by Django 2.1.8 on 2019-07-21 17:49

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_lessonpage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonpage',
            name='slug',
            field=models.CharField(help_text="must be a single string, e.g. 'this-is-an-example'", max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')]),
        ),
    ]
