# Generated by Django 5.1.1 on 2024-10-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0009_course_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
