# Generated by Django 5.1.1 on 2024-11-29 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0010_delete_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"default_related_name": "lessons"},
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="id",
        ),
        migrations.AddField(
            model_name="lesson",
            name="area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="learn.contentarea",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lesson",
            name="slug_field",
            field=models.SlugField(
               primary_key=True, serialize=False, unique=True
            ),
            preserve_default=False,
        ),
    ]
