# Generated by Django 2.2.3 on 2019-08-06 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0011_auto_20190805_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonpage',
            name='next_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.LessonPage'),
        ),
    ]
