# Generated by Django 5.1.1 on 2024-11-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0011_alter_lesson_options_remove_lesson_id_lesson_area_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="slug_field",
            new_name="slug",
        ),
    ]
