# Generated by Django 2.2.3 on 2019-08-08 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0013_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_lesson_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.Course'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_lesson_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.LessonPage'),
        ),
    ]
