# Generated by Django 2.2.3 on 2019-08-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0014_auto_20190807_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonpage',
            name='pic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lessonpage',
            name='snippet_size',
            field=models.IntegerField(default=150),
        ),
    ]
