# Generated by Django 2.2.3 on 2019-08-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0015_auto_20190807_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklistitemcategory',
            options={'verbose_name_plural': 'Task List Item Categories'},
        ),
        migrations.AddField(
            model_name='profile',
            name='course_units_completed',
            field=models.ManyToManyField(to='learn.Unit'),
        ),
        migrations.AlterField(
            model_name='lessonpage',
            name='pic',
            field=models.CharField(blank=True, help_text="This is the 'splash' picture that will be shown for the unit. You can leave it blank. FOR POSTS SERVED UP ON THE SITE, THEY SHOULD START WITH /static/img/", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lessonpage',
            name='snippet_size',
            field=models.IntegerField(default=150, help_text="The snippet_size determines how much of a text to 'preview' before the card shows the 'study' button"),
        ),
    ]
