# Generated by Django 2.2.3 on 2019-08-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0016_auto_20190808_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course_lessons_completed',
            field=models.ManyToManyField(related_name='course_lessons_completed', to='learn.LessonPage'),
        ),
    ]
