# Generated by Django 2.2.3 on 2019-08-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0017_profile_course_lessons_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course_lessons_completed',
            field=models.ManyToManyField(blank=True, null=True, related_name='course_lessons_completed', to='learn.LessonPage'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='course_units_completed',
            field=models.ManyToManyField(blank=True, null=True, to='learn.Unit'),
        ),
    ]
