# Generated by Django 2.2.3 on 2019-08-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0018_auto_20190808_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_weight',
            field=models.IntegerField(blank=True, help_text="should match how many questions are on the BACB's exam", null=True),
        ),
    ]
