# Generated by Django 2.2.3 on 2019-08-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0020_auto_20190808_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course_lessons_completed',
            field=models.ManyToManyField(blank=True, related_name='course_lessons_completed', to='learn.LessonPage'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='course_units_completed',
            field=models.ManyToManyField(blank=True, to='learn.Unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_lessons',
            field=models.ManyToManyField(blank=True, to='learn.LessonPage'),
        ),
    ]
