# Generated by Django 2.2.3 on 2019-08-19 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0021_auto_20190808_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonpage',
            name='last_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_lesson_page', to='learn.LessonPage'),
        ),
        migrations.AlterField(
            model_name='lessonpage',
            name='next_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_lesson_page', to='learn.LessonPage'),
        ),
    ]
