# Generated by Django 2.2.3 on 2019-08-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_quizscoresummary'),
        ('learn', '0022_auto_20190818_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonpage',
            name='lesson_quizzes',
            field=models.ManyToManyField(blank=True, null=True, to='quiz.Form'),
        ),
    ]
