# Generated by Django 2.2.3 on 2019-08-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_quizscoresummary'),
        ('fluency', '0016_fluencytimedscoresummary_fluencyuntimedscoresummary'),
        ('learn', '0023_lessonpage_lesson_quizzes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_quiz_decks_completed',
            field=models.ManyToManyField(blank=True, related_name='course_quiz_forms_completed', to='fluency.Deck'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_quiz_forms_completed',
            field=models.ManyToManyField(blank=True, related_name='course_quiz_forms_completed', to='quiz.Form'),
        ),
    ]
