# Generated by Django 2.2.3 on 2019-08-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0024_auto_20190821_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonpage',
            name='lesson_quizzes',
            field=models.ManyToManyField(blank=True, to='quiz.Form'),
        ),
    ]
