# Generated by Django 2.2.3 on 2019-08-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0025_auto_20190821_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_quiz_decks_completed',
            new_name='user_fluency_decks_completed',
        ),
    ]
