# Generated by Django 2.2.3 on 2019-08-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0026_auto_20190821_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_fluency_decks_completed',
            field=models.ManyToManyField(blank=True, to='fluency.Deck'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_quiz_forms_completed',
            field=models.ManyToManyField(blank=True, to='quiz.Form'),
        ),
    ]
