# Generated by Django 2.2.3 on 2019-08-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0029_auto_20190822_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_button',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='module_subtitle',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
