# Generated by Django 2.2.3 on 2019-08-22 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0033_module_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='module_subtitle',
            new_name='module_title',
        ),
    ]
