# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbtquiz', '0002_auto_20170507_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizchoice',
            name='is_correct',
        ),
    ]
